# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-14 11:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u540d\u79f0')),
                ('students', models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u4eba\u6570')),
                ('click_nums', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6570')),
                ('degree', models.CharField(choices=[('low', '\u521d\u7ea7'), ('middle', '\u4e2d\u7ea7'), ('high', '\u9ad8\u7ea7')], default='high', max_length=10, verbose_name='\u96be\u5ea6')),
                ('length', models.IntegerField(default=0, verbose_name='\u65f6\u957f')),
                ('score', models.IntegerField(default=0, verbose_name='\u8bc4\u5206')),
                ('abstract', models.CharField(max_length=50, verbose_name='\u7b80\u8ff0')),
                ('detail', models.CharField(max_length=100, verbose_name='\u8be6\u7ec6\u63cf\u8ff0')),
                ('image', models.ImageField(max_length=50, upload_to='image/course/%Y/%m', verbose_name='\u56fe\u7247')),
                ('is_fight', models.CharField(choices=[('y', '\u662f'), ('n', '\u5426')], default='n', max_length=1, verbose_name='\u662f\u5426\u5b9e\u6218')),
                ('price', models.IntegerField(default=0, verbose_name='\u4ef7\u683c')),
                ('cloud_service', models.IntegerField(default=0, verbose_name='\u4e91\u670d\u52a1\u5929\u6570')),
                ('add_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b',
                'verbose_name_plural': '\u8bfe\u7a0b',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u540d\u79f0')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b\u7c7b\u578b',
                'verbose_name_plural': '\u8bfe\u7a0b\u7c7b\u578b',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Type', verbose_name='\u7c7b\u578b'),
        ),
    ]
