# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-14 11:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='\u8ba2\u5355\u53f7')),
                ('price', models.IntegerField(default=0, verbose_name='\u603b\u91d1\u989d')),
                ('is_pay', models.BooleanField(default=False, verbose_name='\u662f\u5426\u652f\u4ed8')),
                ('pay_way', models.CharField(choices=[('wx', '\u5fae\u4fe1'), ('zfb', '\u652f\u4ed8\u5b9d')], default='zfb', max_length=3, verbose_name='\u652f\u4ed8\u65b9\u5f0f')),
                ('add_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account', verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u8ba2\u5355',
                'verbose_name_plural': '\u8ba2\u5355',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='\u8bfe\u7a0b')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='\u8ba2\u5355')),
            ],
            options={
                'verbose_name': '\u8ba2\u5355\u8be6\u60c5',
                'verbose_name_plural': '\u8ba2\u5355\u8be6\u60c5',
            },
        ),
    ]
