# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-19 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='\u8ba2\u5355\u53f7'),
        ),
    ]
