# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-20 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20170220_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_pay',
            field=models.IntegerField(choices=[(0, '\u672a\u652f\u4ed8'), (1, '\u5df2\u652f\u4ed8'), (2, '\u5173\u95ed')], default=0, verbose_name='\u662f\u5426\u652f\u4ed8'),
        ),
    ]
