# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-15 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='integral',
            field=models.IntegerField(default=0, verbose_name='\u79ef\u5206'),
        ),
        migrations.AddField(
            model_name='account',
            name='signature',
            field=models.CharField(default='Never give up', max_length=20, verbose_name='\u7b7e\u540d'),
        ),
    ]
